wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: true
    python_version: 3.7.4
batch_size:
  desc: null
  value: 157.1879926630153
epochs:
  desc: null
  value: 332.75690866960235
learning_rate:
  desc: null
  value: 0.4892931942382869
