wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.27
    is_jupyter_run: true
    python_version: 3.7.4
batch_size:
  desc: null
  value: 237.5794787221449
epochs:
  desc: null
  value: 336.86932018359425
learning_rate:
  desc: null
  value: -0.8633034953410278
